// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    areas: {
        name: "areas";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          area: string;
        }>;
      };
    customers: {
        name: "customers";
        parameters: {
          /** STRING - use sql.string() */
          area: SQLStringMarker;
          /** STRING - use sql.string() */
          gender: SQLStringMarker;
          /** STRING - use sql.string() */
          carlife: SQLStringMarker;
          /** STRING - use sql.string() */
          cosmo: SQLStringMarker;
          /** STRING - use sql.string() */
          name_search: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          customer_id: string;
          /** @sqlType STRING */
          last_name: string;
          /** @sqlType STRING */
          first_name: string;
          /** @sqlType DATE */
          birthdate: string;
          /** @sqlType STRING */
          gender: string;
          /** @sqlType STRING */
          area: string;
          /** @sqlType DATE */
          join_date: string;
          /** @sqlType BOOLEAN */
          carlife_square_member: boolean;
          /** @sqlType BOOLEAN */
          cosmo_card_holder: boolean;
        }>;
      };
  }
}
