// Auto-generated by AppKit - DO NOT EDIT
// Generated by 'npx @databricks/appkit generate-types' or Vite plugin during build
import "@databricks/appkit-ui/react";
import type { SQLTypeMarker, SQLStringMarker, SQLNumberMarker, SQLBooleanMarker, SQLBinaryMarker, SQLDateMarker, SQLTimestampMarker } from "@databricks/appkit-ui/js";

declare module "@databricks/appkit-ui/react" {
  interface QueryRegistry {
    customers_counts: {
        name: "customers_counts";
        parameters: {
          /** STRING - use sql.string() */
          areas: SQLStringMarker;
          /** STRING - use sql.string() */
          genders: SQLStringMarker;
          /** STRING - use sql.string() */
          carlife: SQLStringMarker;
          /** STRING - use sql.string() */
          cosmo: SQLStringMarker;
          /** DATE - use sql.date() */
          join_from: SQLDateMarker;
          /** DATE - use sql.date() */
          join_to: SQLDateMarker;
        };
        result: Array<{
          /** @sqlType BIGINT */
          total_count: number;
          /** @sqlType BIGINT */
          filtered_count: number;
        }>;
      };
    customers_filtered: {
        name: "customers_filtered";
        parameters: {
          /** STRING - use sql.string() */
          areas: SQLStringMarker;
          /** STRING - use sql.string() */
          genders: SQLStringMarker;
          /** STRING - use sql.string() */
          carlife: SQLStringMarker;
          /** STRING - use sql.string() */
          cosmo: SQLStringMarker;
          /** DATE - use sql.date() */
          join_from: SQLDateMarker;
          /** DATE - use sql.date() */
          join_to: SQLDateMarker;
          /** INT - use sql.int() */
          row_limit: SQLNumberMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          customer_id: string;
          /** @sqlType STRING */
          last_name: string;
          /** @sqlType STRING */
          first_name: string;
          /** @sqlType DATE */
          birthdate: string;
          /** @sqlType STRING */
          gender: string;
          /** @sqlType STRING */
          area: string;
          /** @sqlType DATE */
          join_date: string;
          /** @sqlType BOOLEAN */
          carlife_square_member: boolean;
          /** @sqlType BOOLEAN */
          cosmo_card_holder: boolean;
        }>;
      };
    customer_areas: {
        name: "customer_areas";
        parameters: Record<string, never>;
        result: Array<{
          /** @sqlType STRING */
          area: string;
        }>;
      };
    saved_filters_list: {
        name: "saved_filters_list";
        parameters: {
          /** STRING - use sql.string() */
          refresh: SQLStringMarker;
        };
        result: Array<{
          /** @sqlType STRING */
          id: string;
          /** @sqlType STRING */
          name: string;
          /** @sqlType STRING */
          filters: string;
          /** @sqlType TIMESTAMP */
          created_at: string;
        }>;
      };
  }
}
